[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_INCLUDE = "optional"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
